version: "3"

tasks:
  default:
    desc: Show this help message
    cmds:
      - "echo 'Usage: task [target]'"
      - echo ''
      - echo 'Available tasks:'
      - task --list

  # Development Commands
  build:
    desc: Build the application
    cmds:
      - go build -o bin/oolio ./cmd/main.go

  run:
    desc: Run the application
    cmds:
      - go run ./cmd/main.go

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  # Database Commands
  sqlc-compile:
    desc: Generate SQLC code
    cmds:
      - sqlc generate

  migrate-up:
    desc: Run database migrations up
    cmds:
      - migrate -path migrations -database "postgresql://oolio:oolio_password@localhost:5432/oolio_db?sslmode=disable" up

  migrate-down:
    desc: Run database migrations down
    cmds:
      - migrate -path migrations -database "postgresql://oolio:oolio_password@localhost:5432/oolio_db?sslmode=disable" down

  migrate-create:
    desc: "Create new migration (usage: task migrate-create -- migration_name)"
    vars:
      NAME: "{{.CLI_ARGS}}"
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.NAME}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  dev-setup:
    desc: Setup development environment
    cmds:
      - go mod download
      - go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  # Docker Commands - Production
  docker-up:
    desc: Start all services (API + Web + DB + Redis)
    cmds:
      - docker-compose up -d

  docker-down:
    desc: Stop all services
    cmds:
      - docker-compose down

  docker-logs:
    desc: Show logs for all services
    cmds:
      - docker-compose logs -f

  docker-build:
    desc: Build Docker images
    cmds:
      - docker-compose build

  docker-restart:
    desc: Restart all services
    cmds:
      - docker-compose restart

  # Docker Commands - Development
  docker-dev:
    desc: Start in development mode with hot reload
    cmds:
      - docker-compose --profile dev up -d

  docker-dev-down:
    desc: Stop development services
    cmds:
      - docker-compose --profile dev down

  docker-dev-logs:
    desc: Show development logs
    cmds:
      - docker-compose --profile dev logs -f

  # Docker Commands - Services Only
  docker-services:
    desc: Start only DB and Redis (for local development)
    cmds:
      - docker-compose up -d db redis

  docker-services-down:
    desc: Stop DB and Redis
    cmds:
      - docker-compose stop db redis

  # Docker Commands - Migration
  docker-migrate:
    desc: Run database migrations in Docker
    cmds:
      - docker-compose --profile migration up migrate

  # Docker Commands - Cleanup
  docker-clean:
    desc: Remove all containers, volumes, and images
    cmds:
      - docker-compose down -v
      - docker system prune -f

  docker-clean-all:
    desc: Remove everything including images
    cmds:
      - docker-compose down -v --rmi all
      - docker system prune -af

  # Docker Commands - Individual Services
  docker-api:
    desc: Start only API service
    cmds:
      - docker-compose up -d api

  docker-web:
    desc: Start only Web service
    cmds:
      - docker-compose up -d web

  docker-db:
    desc: Start only Database service
    cmds:
      - docker-compose up -d db

  docker-redis:
    desc: Start only Redis service
    cmds:
      - docker-compose up -d redis
