// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Order struct {
	ID        uuid.UUID
	Total     string
	Discounts sql.NullString
	Status    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type OrderItem struct {
	ID          uuid.UUID
	OrderID     uuid.NullUUID
	ProductID   uuid.NullUUID
	Quantity    int32
	PriceAtTime string
	CreatedAt   sql.NullTime
}

type Product struct {
	ID           uuid.UUID
	Name         string
	Price        string
	Category     string
	ThumbnailUrl sql.NullString
	MobileUrl    sql.NullString
	TabletUrl    sql.NullString
	DesktopUrl   sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
