// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, price, category, thumbnail_url, mobile_url, tablet_url, desktop_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, price, category, thumbnail_url, mobile_url, tablet_url, desktop_url, created_at, updated_at
`

type CreateProductParams struct {
	Name         string
	Price        string
	Category     string
	ThumbnailUrl sql.NullString
	MobileUrl    sql.NullString
	TabletUrl    sql.NullString
	DesktopUrl   sql.NullString
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Price,
		arg.Category,
		arg.ThumbnailUrl,
		arg.MobileUrl,
		arg.TabletUrl,
		arg.DesktopUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Category,
		&i.ThumbnailUrl,
		&i.MobileUrl,
		&i.TabletUrl,
		&i.DesktopUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, price, category, thumbnail_url, mobile_url, tablet_url, desktop_url, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Category,
		&i.ThumbnailUrl,
		&i.MobileUrl,
		&i.TabletUrl,
		&i.DesktopUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT id, name, price, category, thumbnail_url, mobile_url, tablet_url, desktop_url, created_at, updated_at
FROM products
ORDER BY name
`

func (q *Queries) GetProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Category,
			&i.ThumbnailUrl,
			&i.MobileUrl,
			&i.TabletUrl,
			&i.DesktopUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products 
SET name = $2, price = $3, category = $4, thumbnail_url = $5, mobile_url = $6, tablet_url = $7, desktop_url = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, name, price, category, thumbnail_url, mobile_url, tablet_url, desktop_url, created_at, updated_at
`

type UpdateProductParams struct {
	ID           uuid.UUID
	Name         string
	Price        string
	Category     string
	ThumbnailUrl sql.NullString
	MobileUrl    sql.NullString
	TabletUrl    sql.NullString
	DesktopUrl   sql.NullString
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Category,
		arg.ThumbnailUrl,
		arg.MobileUrl,
		arg.TabletUrl,
		arg.DesktopUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Category,
		&i.ThumbnailUrl,
		&i.MobileUrl,
		&i.TabletUrl,
		&i.DesktopUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
